### ISSUE TITLE
Propose to add new fluent operator maintainers as the fluent org members

### ISSUE THREAD

**Issue by benjaminhuo** [fluent/fluent-bit-infra#184]
Hi @agup006 and @patrick-stephens, In the last few months, there're a few people are added as fluent operator maintainers because of their significant contribution to the fluent operator project, so I propose to add them as fluent org members as well, they're:

@adiforluls 
@jjsiv 
@momoXD007 
@Kristian-ZH 
@mango 
@zhangpeng

Benjamin

**Comment by patrick-stephens** [comment]
Sure, let me sort.

**Comment by patrick-stephens** [comment]
@adiforluls ha a pending invitation already

**Comment by adiforluls** [comment]
Hi @patrick-stephens @agup006, I accepted the invite to become fluent-operator collaborator/member yesterday sometime after this thread was closed, I don't see myself listed as a fluent org member https://github.com/orgs/fluent/people
Can you help here? Thanks in advance!

**Comment by patrick-stephens** [comment]
Please enable 2FA everyone too - it will be a requirement if you contribute to Fluent, enforced by Github as well.

**Comment by patrick-stephens** [comment]
done
